# Generated by Django 5.1 on 2024-08-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tole_Samiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tole_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tole_Samiti_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('tole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tole_samiti_members', to='forest.tole_samiti')),
            ],
        ),
    ]
