# Generated by Django 5.1 on 2024-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_tole_samiti_tole_samiti_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tole_samiti_member',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='tole_member_images/'),
        ),
    ]
