# Generated by Django 5.1 on 2024-08-31 14:24

import forest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0003_tole_samiti_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tole_samiti_member',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=forest.models.tole_member_image_upload_path),
        ),
    ]
