# Generated by Django 5.1 on 2024-08-31 14:37

import django.db.models.deletion
import forest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0004_alter_tole_samiti_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chetriya_Samiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chetra_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chetriya_Samiti_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_image.jpg', upload_to=forest.models.chetriya_member_image_upload_path)),
                ('chetra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chetra_samiti_members', to='forest.chetriya_samiti')),
            ],
        ),
    ]
