# Generated by Django 5.1 on 2024-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0005_chetriya_samiti_chetriya_samiti_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chetriya_samiti_member',
            name='position',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('advisor', 'Advisor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tole_samiti_member',
            name='position',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('advisor', 'Advisor')], max_length=100),
        ),
    ]
