# Generated by Django 5.1 on 2024-09-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0006_alter_chetriya_samiti_member_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karya_Samiti_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('advisor', 'Advisor')], max_length=100)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='images/karya_samiti')),
            ],
        ),
        migrations.CreateModel(
            name='Lekha_Samiti_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('advisor', 'Advisor')], max_length=100)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='images/lekha_samiti')),
            ],
        ),
        migrations.CreateModel(
            name='Salakar_Samiti_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('advisor', 'Advisor')], max_length=100)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='images/lekha_samiti')),
            ],
        ),
    ]
